package com.example.my_weather_forecast.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp

@Immutable
data class WeatherColors(
    val canvas: Color,
    val canvasSecondary: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceMuted: Color,
    val weatherSurface: Color,
    val searchField: Color,
    val searchFieldFocused: Color,
    val searchResultPressed: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textInverse: Color,
    val iconPrimary: Color,
    val iconSecondary: Color,
    val border: Color,
    val divider: Color,
    val focus: Color,
    val accent: Color,
    val accentPressed: Color,
    val onAccent: Color,
    val success: Color,
    val warning: Color,
    val error: Color,
    val info: Color,
    val scrim: Color,
)

object WeatherColorSchemes {
    val Light = WeatherColors(
        canvas = Color(0xFFF7F8F6),
        canvasSecondary = Color(0xFFF1F4F2),
        surface = Color(0xFFFFFFFF),
        surfaceElevated = Color(0xFFFCFDFC),
        surfaceMuted = Color(0xFFEEF2F1),
        weatherSurface = Color(0xE8FFFFFF),
        searchField = Color(0xFFEDF3F2),
        searchFieldFocused = Color(0xFFF7FBFA),
        searchResultPressed = Color(0xFFE5EFED),
        textPrimary = Color(0xFF1C2528),
        textSecondary = Color(0xFF556267),
        textTertiary = Color(0xFF687477),
        textInverse = Color(0xFFF7FAFA),
        iconPrimary = Color(0xFF344448),
        iconSecondary = Color(0xFF687477),
        border = Color(0xFFCBD7D7),
        divider = Color(0xFFDDE5E4),
        focus = Color(0xFF3D7F83),
        accent = Color(0xFF3D7F83),
        accentPressed = Color(0xFF2F686C),
        onAccent = Color.White,
        success = Color(0xFF2F6B4F),
        warning = Color(0xFF765700),
        error = Color(0xFFB3261E),
        info = Color(0xFF3D6B91),
        scrim = Color(0x520F171A),
    )

    val Dark = WeatherColors(
        canvas = Color(0xFF151B1E),
        canvasSecondary = Color(0xFF192125),
        surface = Color(0xFF1D2529),
        surfaceElevated = Color(0xFF263034),
        surfaceMuted = Color(0xFF222C30),
        weatherSurface = Color(0xE61D2529),
        searchField = Color(0xFF263135),
        searchFieldFocused = Color(0xFF2B383C),
        searchResultPressed = Color(0xFF303D41),
        textPrimary = Color(0xFFEAF1F1),
        textSecondary = Color(0xFFBAC5C5),
        textTertiary = Color(0xFF929FA1),
        textInverse = Color(0xFF151B1E),
        iconPrimary = Color(0xFFD7E1E1),
        iconSecondary = Color(0xFF9EABAD),
        border = Color(0xFF3A484D),
        divider = Color(0xFF303C41),
        focus = Color(0xFF8AC9CB),
        accent = Color(0xFF8AC9CB),
        accentPressed = Color(0xFFA0D9DA),
        onAccent = Color(0xFF153033),
        success = Color(0xFF8DD4AE),
        warning = Color(0xFFEECB78),
        error = Color(0xFFFFB4AB),
        info = Color(0xFFA8CBE8),
        scrim = Color(0x99070B0D),
    )
}

internal fun weatherColorScheme(darkTheme: Boolean): ColorScheme {
    val colors = if (darkTheme) WeatherColorSchemes.Dark else WeatherColorSchemes.Light
    return if (darkTheme) {
        darkColorScheme(
            primary = colors.accent,
            onPrimary = colors.onAccent,
            primaryContainer = colors.searchResultPressed,
            onPrimaryContainer = colors.textPrimary,
            secondary = colors.info,
            onSecondary = colors.canvas,
            secondaryContainer = colors.surfaceMuted,
            onSecondaryContainer = colors.textPrimary,
            tertiary = colors.warning,
            onTertiary = colors.canvas,
            error = colors.error,
            onError = colors.canvas,
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = colors.canvas,
            onBackground = colors.textPrimary,
            surface = colors.surface,
            onSurface = colors.textPrimary,
            surfaceVariant = colors.surfaceMuted,
            onSurfaceVariant = colors.textSecondary,
            outline = colors.border,
            outlineVariant = colors.divider,
            scrim = colors.scrim,
            inverseSurface = colors.textPrimary,
            inverseOnSurface = colors.canvas,
            inversePrimary = WeatherColorSchemes.Light.accent,
            surfaceTint = colors.accent,
        )
    } else {
        lightColorScheme(
            primary = colors.accent,
            onPrimary = colors.onAccent,
            primaryContainer = colors.searchResultPressed,
            onPrimaryContainer = colors.textPrimary,
            secondary = colors.info,
            onSecondary = Color.White,
            secondaryContainer = colors.surfaceMuted,
            onSecondaryContainer = colors.textPrimary,
            tertiary = colors.warning,
            onTertiary = Color.White,
            error = colors.error,
            onError = Color.White,
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = colors.canvas,
            onBackground = colors.textPrimary,
            surface = colors.surface,
            onSurface = colors.textPrimary,
            surfaceVariant = colors.surfaceMuted,
            onSurfaceVariant = colors.textSecondary,
            outline = colors.border,
            outlineVariant = colors.divider,
            scrim = colors.scrim,
            inverseSurface = colors.textPrimary,
            inverseOnSurface = colors.canvas,
            inversePrimary = WeatherColorSchemes.Dark.accent,
            surfaceTint = colors.accent,
        )
    }
}

internal fun lerpColorSchemes(
    start: ColorScheme,
    stop: ColorScheme,
    fraction: Float,
): ColorScheme = ColorScheme(
    primary = lerp(start.primary, stop.primary, fraction),
    onPrimary = lerp(start.onPrimary, stop.onPrimary, fraction),
    primaryContainer = lerp(start.primaryContainer, stop.primaryContainer, fraction),
    onPrimaryContainer = lerp(start.onPrimaryContainer, stop.onPrimaryContainer, fraction),
    inversePrimary = lerp(start.inversePrimary, stop.inversePrimary, fraction),
    secondary = lerp(start.secondary, stop.secondary, fraction),
    onSecondary = lerp(start.onSecondary, stop.onSecondary, fraction),
    secondaryContainer = lerp(start.secondaryContainer, stop.secondaryContainer, fraction),
    onSecondaryContainer = lerp(start.onSecondaryContainer, stop.onSecondaryContainer, fraction),
    tertiary = lerp(start.tertiary, stop.tertiary, fraction),
    onTertiary = lerp(start.onTertiary, stop.onTertiary, fraction),
    tertiaryContainer = lerp(start.tertiaryContainer, stop.tertiaryContainer, fraction),
    onTertiaryContainer = lerp(start.onTertiaryContainer, stop.onTertiaryContainer, fraction),
    background = lerp(start.background, stop.background, fraction),
    onBackground = lerp(start.onBackground, stop.onBackground, fraction),
    surface = lerp(start.surface, stop.surface, fraction),
    onSurface = lerp(start.onSurface, stop.onSurface, fraction),
    surfaceVariant = lerp(start.surfaceVariant, stop.surfaceVariant, fraction),
    onSurfaceVariant = lerp(start.onSurfaceVariant, stop.onSurfaceVariant, fraction),
    surfaceTint = lerp(start.surfaceTint, stop.surfaceTint, fraction),
    inverseSurface = lerp(start.inverseSurface, stop.inverseSurface, fraction),
    inverseOnSurface = lerp(start.inverseOnSurface, stop.inverseOnSurface, fraction),
    error = lerp(start.error, stop.error, fraction),
    onError = lerp(start.onError, stop.onError, fraction),
    errorContainer = lerp(start.errorContainer, stop.errorContainer, fraction),
    onErrorContainer = lerp(start.onErrorContainer, stop.onErrorContainer, fraction),
    outline = lerp(start.outline, stop.outline, fraction),
    outlineVariant = lerp(start.outlineVariant, stop.outlineVariant, fraction),
    scrim = lerp(start.scrim, stop.scrim, fraction),
    surfaceBright = lerp(start.surfaceBright, stop.surfaceBright, fraction),
    surfaceDim = lerp(start.surfaceDim, stop.surfaceDim, fraction),
    surfaceContainer = lerp(start.surfaceContainer, stop.surfaceContainer, fraction),
    surfaceContainerHigh = lerp(start.surfaceContainerHigh, stop.surfaceContainerHigh, fraction),
    surfaceContainerHighest = lerp(
        start.surfaceContainerHighest,
        stop.surfaceContainerHighest,
        fraction,
    ),
    surfaceContainerLow = lerp(start.surfaceContainerLow, stop.surfaceContainerLow, fraction),
    surfaceContainerLowest = lerp(start.surfaceContainerLowest, stop.surfaceContainerLowest, fraction),
)

internal fun lerpWeatherColors(
    start: WeatherColors,
    stop: WeatherColors,
    fraction: Float,
): WeatherColors = WeatherColors(
    canvas = lerp(start.canvas, stop.canvas, fraction),
    canvasSecondary = lerp(start.canvasSecondary, stop.canvasSecondary, fraction),
    surface = lerp(start.surface, stop.surface, fraction),
    surfaceElevated = lerp(start.surfaceElevated, stop.surfaceElevated, fraction),
    surfaceMuted = lerp(start.surfaceMuted, stop.surfaceMuted, fraction),
    weatherSurface = lerp(start.weatherSurface, stop.weatherSurface, fraction),
    searchField = lerp(start.searchField, stop.searchField, fraction),
    searchFieldFocused = lerp(start.searchFieldFocused, stop.searchFieldFocused, fraction),
    searchResultPressed = lerp(start.searchResultPressed, stop.searchResultPressed, fraction),
    textPrimary = lerp(start.textPrimary, stop.textPrimary, fraction),
    textSecondary = lerp(start.textSecondary, stop.textSecondary, fraction),
    textTertiary = lerp(start.textTertiary, stop.textTertiary, fraction),
    textInverse = lerp(start.textInverse, stop.textInverse, fraction),
    iconPrimary = lerp(start.iconPrimary, stop.iconPrimary, fraction),
    iconSecondary = lerp(start.iconSecondary, stop.iconSecondary, fraction),
    border = lerp(start.border, stop.border, fraction),
    divider = lerp(start.divider, stop.divider, fraction),
    focus = lerp(start.focus, stop.focus, fraction),
    accent = lerp(start.accent, stop.accent, fraction),
    accentPressed = lerp(start.accentPressed, stop.accentPressed, fraction),
    onAccent = lerp(start.onAccent, stop.onAccent, fraction),
    success = lerp(start.success, stop.success, fraction),
    warning = lerp(start.warning, stop.warning, fraction),
    error = lerp(start.error, stop.error, fraction),
    info = lerp(start.info, stop.info, fraction),
    scrim = lerp(start.scrim, stop.scrim, fraction),
)
