package com.example.my_weather_forecast.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class WeatherColors(
    val canvas: Color,
    val canvasSecondary: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceMuted: Color,
    val weatherSurface: Color,
    val searchField: Color,
    val searchFieldFocused: Color,
    val searchResultPressed: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textInverse: Color,
    val iconPrimary: Color,
    val iconSecondary: Color,
    val border: Color,
    val divider: Color,
    val focus: Color,
    val accent: Color,
    val accentPressed: Color,
    val onAccent: Color,
    val success: Color,
    val warning: Color,
    val error: Color,
    val info: Color,
    val scrim: Color,
)

object WeatherColorSchemes {
    val Light = WeatherColors(
        canvas = Color(0xFFF7F8F6),
        canvasSecondary = Color(0xFFF1F4F2),
        surface = Color(0xFFFFFFFF),
        surfaceElevated = Color(0xFFFCFDFC),
        surfaceMuted = Color(0xFFEEF2F1),
        weatherSurface = Color(0xE8FFFFFF),
        searchField = Color(0xFFEDF3F2),
        searchFieldFocused = Color(0xFFF7FBFA),
        searchResultPressed = Color(0xFFE5EFED),
        textPrimary = Color(0xFF1C2528),
        textSecondary = Color(0xFF556267),
        textTertiary = Color(0xFF687477),
        textInverse = Color(0xFFF7FAFA),
        iconPrimary = Color(0xFF344448),
        iconSecondary = Color(0xFF687477),
        border = Color(0xFFCBD7D7),
        divider = Color(0xFFDDE5E4),
        focus = Color(0xFF3D7F83),
        accent = Color(0xFF3D7F83),
        accentPressed = Color(0xFF2F686C),
        onAccent = Color.White,
        success = Color(0xFF2F6B4F),
        warning = Color(0xFF765700),
        error = Color(0xFFB3261E),
        info = Color(0xFF3D6B91),
        scrim = Color(0x520F171A),
    )

    val Dark = WeatherColors(
        canvas = Color(0xFF151B1E),
        canvasSecondary = Color(0xFF192125),
        surface = Color(0xFF1D2529),
        surfaceElevated = Color(0xFF263034),
        surfaceMuted = Color(0xFF222C30),
        weatherSurface = Color(0xE61D2529),
        searchField = Color(0xFF263135),
        searchFieldFocused = Color(0xFF2B383C),
        searchResultPressed = Color(0xFF303D41),
        textPrimary = Color(0xFFEAF1F1),
        textSecondary = Color(0xFFBAC5C5),
        textTertiary = Color(0xFF929FA1),
        textInverse = Color(0xFF151B1E),
        iconPrimary = Color(0xFFD7E1E1),
        iconSecondary = Color(0xFF9EABAD),
        border = Color(0xFF3A484D),
        divider = Color(0xFF303C41),
        focus = Color(0xFF8AC9CB),
        accent = Color(0xFF8AC9CB),
        accentPressed = Color(0xFFA0D9DA),
        onAccent = Color(0xFF153033),
        success = Color(0xFF8DD4AE),
        warning = Color(0xFFEECB78),
        error = Color(0xFFFFB4AB),
        info = Color(0xFFA8CBE8),
        scrim = Color(0x99070B0D),
    )
}

internal fun weatherColorScheme(darkTheme: Boolean): ColorScheme {
    val colors = if (darkTheme) WeatherColorSchemes.Dark else WeatherColorSchemes.Light
    return if (darkTheme) {
        darkColorScheme(
            primary = colors.accent,
            onPrimary = colors.onAccent,
            primaryContainer = colors.searchResultPressed,
            onPrimaryContainer = colors.textPrimary,
            secondary = colors.info,
            onSecondary = colors.canvas,
            secondaryContainer = colors.surfaceMuted,
            onSecondaryContainer = colors.textPrimary,
            tertiary = colors.warning,
            onTertiary = colors.canvas,
            error = colors.error,
            onError = colors.canvas,
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = colors.canvas,
            onBackground = colors.textPrimary,
            surface = colors.surface,
            onSurface = colors.textPrimary,
            surfaceVariant = colors.surfaceMuted,
            onSurfaceVariant = colors.textSecondary,
            outline = colors.border,
            outlineVariant = colors.divider,
            scrim = colors.scrim,
            inverseSurface = colors.textPrimary,
            inverseOnSurface = colors.canvas,
            inversePrimary = WeatherColorSchemes.Light.accent,
            surfaceTint = colors.accent,
        )
    } else {
        lightColorScheme(
            primary = colors.accent,
            onPrimary = colors.onAccent,
            primaryContainer = colors.searchResultPressed,
            onPrimaryContainer = colors.textPrimary,
            secondary = colors.info,
            onSecondary = Color.White,
            secondaryContainer = colors.surfaceMuted,
            onSecondaryContainer = colors.textPrimary,
            tertiary = colors.warning,
            onTertiary = Color.White,
            error = colors.error,
            onError = Color.White,
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = colors.canvas,
            onBackground = colors.textPrimary,
            surface = colors.surface,
            onSurface = colors.textPrimary,
            surfaceVariant = colors.surfaceMuted,
            onSurfaceVariant = colors.textSecondary,
            outline = colors.border,
            outlineVariant = colors.divider,
            scrim = colors.scrim,
            inverseSurface = colors.textPrimary,
            inverseOnSurface = colors.canvas,
            inversePrimary = WeatherColorSchemes.Dark.accent,
            surfaceTint = colors.accent,
        )
    }
}
